// <auto-generated />
namespace WebApiTest.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Extend_IdentityUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Extend_IdentityUser));
        
        string IMigrationMetadata.Id
        {
            get { return "202010281155175_Extend_IdentityUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
