//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favorite
    {
        public System.Guid FavoriteID { get; set; }
        public Nullable<System.Guid> GameID { get; set; }
        public string UserID { get; set; }
        public System.DateTime DateFavorite { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Game Game { get; set; }
    }
}
