//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public System.Guid NewsID { get; set; }
        public string NewsURL { get; set; }
        public string ArticleTitle { get; set; }
        public string NewsThumbnail { get; set; }
    }
}
